package Interfaces;

import java.awt.event.FocusEvent;
import java.io.File;
import javax.swing.JOptionPane;

import Classes.Customer;
import Classes.Staff;
import Classes.Admin;
	public class LoginInterface extends javax.swing.JFrame {

	    /**
	     * Creates new form LoginInterface
	     */
		public LoginInterface() {
	        initComponents();
	        username.setText("");
	        password.setText("     ");
	    }
		
	    public LoginInterface(String username) {
	        initComponents();
	        this.username.setText(username);
	        password.setText("");
	    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        customer = new javax.swing.JRadioButton();
        staff = new javax.swing.JRadioButton();
        LogBut = new javax.swing.JButton();
        RegBut = new javax.swing.JButton();
        ExitBut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/MCDEliverynew.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 0, 400, 148);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 210, 140, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 260, 150, 30);

        username.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(username);
        username.setBounds(200, 220, 220, 30);

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.setText("     ");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(200, 270, 220, 40);

        buttonGroup1.add(customer);
        customer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customer.setSelected(true);
        customer.setText("Customer");
        getContentPane().add(customer);
        customer.setBounds(130, 313, 140, 40);

        buttonGroup1.add(staff);
        staff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        staff.setText("Staff / Admin");
        getContentPane().add(staff);
        staff.setBounds(310, 313, 130, 40);

        LogBut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LogBut.setText("Login");
        LogBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogButActionPerformed(evt);
            }
        });
        getContentPane().add(LogBut);
        LogBut.setBounds(50, 360, 130, 90);

        RegBut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegBut.setText("No Account ? Register");
        RegBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButActionPerformed(evt);
            }
        });
        getContentPane().add(RegBut);
        RegBut.setBounds(200, 360, 240, 90);

        ExitBut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitBut.setText("EXIT");
        ExitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBut);
        ExitBut.setBounds(460, 360, 100, 90);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LOGIN PAGE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 150, 230, 60);

        pack();
    }// </editor-fold>                        

    private void ExitButActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    	int decision = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit ?");
    	if(decision==JOptionPane.YES_OPTION)
    	{
    		JOptionPane.showMessageDialog(null, "Thank you for choosing us. \nWe hope to see you again.");
    		System.exit(0);
    	}
    }                                       

    private void RegButActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    	RegisterInterface reg1= new RegisterInterface();
    	reg1.setVisible(true);
    	setVisible(false);
    }                                      

    private void LogButActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    	if(customer.isSelected())
    	{
    		Customer cust1 = new Customer();
    		boolean result=cust1.Login(username.getText(), String.valueOf(password.getPassword()), "Customer");
    		if(result)
    		{
    			MenuInterface interface1 = new MenuInterface(username.getText());
    			interface1.setVisible(true);
    			setVisible(false);
    		}
    		else
    		{
    			JOptionPane.showMessageDialog(null, "Mismatched username and password");
    		}
    	}      
    	else if(staff.isSelected())
    	{
    		Staff staff1 = new Staff();
    		Admin admin1= new Admin();
    		boolean result=staff1.Login(username.getText(), String.valueOf(password.getPassword()), "Staff");
    		if(result)
    		{
    			AllOrderInterface interface1 = new AllOrderInterface(username.getText(), "Staff");
    			interface1.setVisible(true);
    			setVisible(false);
    		}
    		else
    		{
    			result=admin1.Login(username.getText(), String.valueOf(password.getPassword()), "Admin");
    			AllOrderInterface interface1 = new AllOrderInterface(username.getText(), "Admin");
    			interface1.setVisible(true);
    			setVisible(false);
    		}
    	}
    }                                      

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {                                     
        // TODO add your handling code here:
    	{
    		if(String.valueOf(this.password.getPassword()).equals("     "))
            password.setText("");
        }
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ExitBut;
    private javax.swing.JButton LogBut;
    private javax.swing.JButton RegBut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JRadioButton staff;
    private javax.swing.JTextField username;
    // End of variables declaration                   
}



